const fs = require('fs');
const path = require('path');
const base = __dirname + '/apps';

function tmpl(title, icon, accent, bodyHTML, script) {
return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>${title}</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:'Inter',sans-serif;background:#0a0a14;color:#eee;min-height:100vh;padding:24px}
.hdr{display:flex;align-items:center;gap:10px;margin-bottom:20px;padding-bottom:14px;border-bottom:1px solid rgba(255,255,255,.08)}.hdr h1{font-size:20px;font-weight:700}.hdr .ico{font-size:28px}
.bdg{padding:3px 10px;background:${accent}22;color:${accent};border-radius:20px;font-size:10px;font-weight:600}
.crd{background:#12122a;border:1px solid rgba(255,255,255,.08);border-radius:12px;padding:20px;margin-bottom:16px;transition:border-color .2s}.crd:hover{border-color:rgba(255,255,255,.15)}
.crd h3{font-size:15px;margin-bottom:8px;color:${accent}}.crd p{font-size:13px;color:#888;line-height:1.6}
.btn{display:inline-flex;align-items:center;gap:6px;padding:10px 20px;background:${accent};color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;font-family:inherit;transition:transform .15s}.btn:hover{transform:translateY(-2px)}
.btn-o{background:transparent;border:1px solid rgba(255,255,255,.08);color:#aaa}.btn-o:hover{border-color:${accent};color:${accent}}
.btn-d{background:#ef4444}.btn-sm{padding:6px 12px;font-size:11px}
input,textarea,select{width:100%;padding:10px 14px;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.08);border-radius:8px;color:#eee;font-family:inherit;font-size:13px;outline:none;margin-bottom:12px}
input:focus,textarea:focus,select:focus{border-color:${accent}}textarea{resize:vertical;min-height:80px}select option{background:#12122a}
label{display:block;font-size:11px;font-weight:600;color:#666;margin-bottom:4px;text-transform:uppercase;letter-spacing:.5px}
.fg{margin-bottom:14px}
.g2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.g3{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}
.sg{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:12px;margin-bottom:20px}
.sb{background:#12122a;border:1px solid rgba(255,255,255,.08);border-radius:10px;padding:14px;text-align:center}
.sb .v{font-size:22px;font-weight:800;color:${accent}}.sb .l{font-size:10px;color:#666;margin-top:4px;text-transform:uppercase}
.li{display:flex;align-items:center;gap:12px;padding:12px 16px;background:#12122a;border:1px solid rgba(255,255,255,.08);border-radius:10px;margin-bottom:8px;transition:all .2s}.li:hover{border-color:rgba(255,255,255,.15);transform:translateX(4px)}
.li .ic{width:36px;height:36px;border-radius:8px;background:${accent}15;display:flex;align-items:center;justify-content:center;font-size:16px;flex-shrink:0}
.li .ct{flex:1}.li .tt{font-size:13px;font-weight:600}.li .st{font-size:11px;color:#666;margin-top:2px}
.tabs{display:flex;gap:4px;background:rgba(255,255,255,.03);border-radius:10px;padding:4px;margin-bottom:20px}
.tab{flex:1;padding:8px;text-align:center;border-radius:8px;font-size:12px;font-weight:600;color:#666;cursor:pointer;border:none;background:none;font-family:inherit;transition:all .2s}
.tab.on{background:${accent};color:#fff}.tab:hover:not(.on){color:#eee;background:rgba(255,255,255,.05)}
.pb{height:8px;background:rgba(255,255,255,.08);border-radius:8px;overflow:hidden;margin-top:6px}.pf{height:100%;background:${accent};border-radius:8px;transition:width .5s}
.tbl{width:100%;border-collapse:collapse;font-size:13px}.tbl th,.tbl td{padding:10px 14px;text-align:left;border-bottom:1px solid rgba(255,255,255,.06)}.tbl th{font-size:10px;text-transform:uppercase;color:#666;letter-spacing:.5px}
.tag{display:inline-block;padding:2px 8px;border-radius:12px;font-size:10px;font-weight:600;background:${accent}18;color:${accent};margin-right:4px}
.empty{text-align:center;padding:48px;color:#444}.empty span{font-size:48px;display:block;margin-bottom:12px}
.flex{display:flex;gap:12px;align-items:center}.flexb{display:flex;justify-content:space-between;align-items:center}
.mt{margin-top:16px}.mb{margin-bottom:16px}
.del{background:none;border:none;color:#555;cursor:pointer;font-size:14px;padding:2px}.del:hover{color:#ef4444}
@media(max-width:600px){.g2,.g3{grid-template-columns:1fr}.sg{grid-template-columns:1fr 1fr}}
</style></head><body>
<div class="hdr"><span class="ico">${icon}</span><h1>${title}</h1><span class="bdg">Full-Stack App</span></div>
${bodyHTML}
<script>${script}</script>
</body></html>`;
}

const apps = [
// [folder, file, title, icon, accent, bodyHTML, script]
// SAAS 5-20
['saas','subscription-tracker.html','Subscription Tracker','🔄','#7c5cff',
'<div class="sg"><div class="sb"><div class="v" id="tc">0</div><div class="l">Total</div></div><div class="sb"><div class="v" id="mc">$0</div><div class="l">Monthly</div></div><div class="sb"><div class="v" id="yc">$0</div><div class="l">Yearly</div></div></div><div class="crd"><div class="g2"><input id="sn" placeholder="Service name"><input id="sp" type="number" placeholder="Monthly cost ($)"></div><div class="g2"><input id="sd" type="date"><select id="sc"><option>Entertainment</option><option>Software</option><option>Cloud</option><option>Other</option></select></div><button class="btn" onclick="addSub()">+ Add Subscription</button></div><div id="list"></div>',
'const K="subs_data";let subs=JSON.parse(localStorage.getItem(K)||"[]");function save(){localStorage.setItem(K,JSON.stringify(subs))}function addSub(){const n=document.getElementById("sn").value.trim();const p=parseFloat(document.getElementById("sp").value);if(!n||!p)return;subs.push({name:n,price:p,date:document.getElementById("sd").value,cat:document.getElementById("sc").value,id:Date.now()});document.getElementById("sn").value="";document.getElementById("sp").value="";save();render()}function del(id){subs=subs.filter(s=>s.id!==id);save();render()}function render(){const list=document.getElementById("list");list.innerHTML=subs.map(s=>`<div class="li"><div class="ic">💳</div><div class="ct"><div class="tt">${s.name}</div><div class="st">${s.cat} • ${s.date||"No date"}</div></div><div style="font-weight:700;color:#7c5cff">$${s.price}/mo</div><button class="del" onclick="del(${s.id})">✕</button></div>`).join("")||\'<div class="empty"><span>🔄</span>No subscriptions yet</div>\';document.getElementById("tc").textContent=subs.length;const m=subs.reduce((a,s)=>a+s.price,0);document.getElementById("mc").textContent="$"+m.toFixed(0);document.getElementById("yc").textContent="$"+(m*12).toFixed(0)}render()'],

['saas','resume-builder.html','Resume Builder','📄','#7c5cff',
'<div class="tabs"><button class="tab on" onclick="showTab(0,this)">Edit</button><button class="tab" onclick="showTab(1,this)">Preview</button></div><div id="t0"><div class="crd"><h3>Personal Info</h3><div class="g2"><div class="fg"><label>Full Name</label><input id="rn" placeholder="John Doe" oninput="updatePreview()"></div><div class="fg"><label>Email</label><input id="re" placeholder="john@email.com" oninput="updatePreview()"></div></div><div class="g2"><div class="fg"><label>Phone</label><input id="rp" placeholder="+1 234 567 890" oninput="updatePreview()"></div><div class="fg"><label>Location</label><input id="rl" placeholder="New York, USA" oninput="updatePreview()"></div></div></div><div class="crd"><h3>Summary</h3><textarea id="rs" placeholder="Brief professional summary..." oninput="updatePreview()"></textarea></div><div class="crd"><h3>Skills (comma separated)</h3><input id="rsk" placeholder="JavaScript, React, Node.js..." oninput="updatePreview()"></div><div class="crd"><h3>Experience</h3><div id="expList"></div><button class="btn btn-sm btn-o mt" onclick="addExp()">+ Add Experience</button></div></div><div id="t1" style="display:none"><div id="preview" style="background:#fff;color:#222;padding:40px;border-radius:12px;max-width:700px;margin:auto;font-size:13px;line-height:1.6"></div><button class="btn mt" onclick="printResume()">📄 Export / Print</button></div>',
'let exps=[];function showTab(i,btn){document.querySelectorAll(".tab").forEach(t=>t.classList.remove("on"));btn.classList.add("on");document.getElementById("t0").style.display=i===0?"":"none";document.getElementById("t1").style.display=i===1?"":"none";if(i===1)updatePreview()}function addExp(){exps.push({title:"",company:"",period:""});renderExps()}function renderExps(){document.getElementById("expList").innerHTML=exps.map((e,i)=>`<div class="crd" style="border-left:3px solid #7c5cff"><div class="g2"><input placeholder="Job Title" value="${e.title}" onchange="exps[${i}].title=this.value"><input placeholder="Company" value="${e.company}" onchange="exps[${i}].company=this.value"></div><input placeholder="Period (e.g. 2020-2023)" value="${e.period}" onchange="exps[${i}].period=this.value"><button class="del" onclick="exps.splice(${i},1);renderExps()">✕ Remove</button></div>`).join("")}function updatePreview(){const n=document.getElementById("rn").value||"Your Name";const e=document.getElementById("re").value;const p=document.getElementById("rp").value;const l=document.getElementById("rl").value;const s=document.getElementById("rs").value;const sk=document.getElementById("rsk").value;document.getElementById("preview").innerHTML=`<h1 style="font-size:24px;margin-bottom:4px;color:#222">${n}</h1><p style="color:#666;margin-bottom:16px">${[e,p,l].filter(Boolean).join(" • ")}</p>${s?`<h3 style="color:#7c5cff;font-size:13px;text-transform:uppercase;margin-bottom:6px">Summary</h3><p style="margin-bottom:16px">${s}</p>`:""}<h3 style="color:#7c5cff;font-size:13px;text-transform:uppercase;margin-bottom:6px">Skills</h3><div style="margin-bottom:16px">${sk.split(",").map(s=>`<span style="display:inline-block;padding:3px 10px;background:#7c5cff22;color:#7c5cff;border-radius:12px;font-size:11px;margin:2px">${s.trim()}</span>`).join("")}</div>${exps.length?`<h3 style="color:#7c5cff;font-size:13px;text-transform:uppercase;margin-bottom:8px">Experience</h3>${exps.map(x=>`<div style="margin-bottom:12px;padding-left:12px;border-left:2px solid #7c5cff"><strong>${x.title}</strong> at ${x.company}<br><span style="color:#888;font-size:11px">${x.period}</span></div>`).join("")}`:""}`}function printResume(){const w=window.open();w.document.write(document.getElementById("preview").innerHTML);w.print()}'],

['saas','invoice-generator.html','Invoice Generator','🧾','#7c5cff',
'<div class="crd"><h3>Invoice Details</h3><div class="g2"><div class="fg"><label>Invoice #</label><input id="inum" value="INV-001"></div><div class="fg"><label>Date</label><input type="date" id="idate"></div></div><div class="g2"><div class="fg"><label>From</label><input id="ifrom" placeholder="Your Business Name"></div><div class="fg"><label>To</label><input id="ito" placeholder="Client Name"></div></div></div><div class="crd"><h3>Line Items</h3><div id="items"></div><button class="btn btn-sm btn-o mt" onclick="addItem()">+ Add Item</button></div><div class="sg"><div class="sb"><div class="v" id="subtotal">$0</div><div class="l">Subtotal</div></div><div class="sb"><div class="v" id="tax">$0</div><div class="l">Tax (10%)</div></div><div class="sb"><div class="v" id="total">$0</div><div class="l">Total</div></div></div><button class="btn" onclick="printInvoice()">🖨️ Print Invoice</button>',
'let items=[{desc:"",qty:1,price:0}];function addItem(){items.push({desc:"",qty:1,price:0});renderItems()}function renderItems(){document.getElementById("items").innerHTML=items.map((it,i)=>`<div class="flex mb"><input style="flex:2" placeholder="Description" value="${it.desc}" onchange="items[${i}].desc=this.value"><input type="number" style="flex:0 0 80px" placeholder="Qty" value="${it.qty}" onchange="items[${i}].qty=+this.value;calc()"><input type="number" style="flex:0 0 100px" placeholder="Price" value="${it.price}" onchange="items[${i}].price=+this.value;calc()"><button class="del" onclick="items.splice(${i},1);renderItems();calc()">✕</button></div>`).join("");calc()}function calc(){const sub=items.reduce((a,it)=>a+it.qty*it.price,0);const tx=sub*.1;document.getElementById("subtotal").textContent="$"+sub.toFixed(2);document.getElementById("tax").textContent="$"+tx.toFixed(2);document.getElementById("total").textContent="$"+(sub+tx).toFixed(2)}function printInvoice(){const w=window.open();w.document.write("<h1>Invoice "+document.getElementById("inum").value+"</h1><p>From: "+document.getElementById("ifrom").value+"</p><p>To: "+document.getElementById("ito").value+"</p><p>Date: "+document.getElementById("idate").value+"</p><hr><table border=1 cellpadding=8 style=border-collapse:collapse;width:100%><tr><th>Description</th><th>Qty</th><th>Price</th><th>Amount</th></tr>"+items.map(it=>"<tr><td>"+it.desc+"</td><td>"+it.qty+"</td><td>$"+it.price+"</td><td>$"+(it.qty*it.price).toFixed(2)+"</td></tr>").join("")+"</table><h2>Total: "+document.getElementById("total").textContent+"</h2>");w.print()}renderItems()'],

['saas','meeting-scheduler.html','Meeting Scheduler','📅','#7c5cff',
'<div class="crd"><h3>Schedule Meeting</h3><div class="fg"><label>Title</label><input id="mt" placeholder="Meeting title"></div><div class="g2"><div class="fg"><label>Date</label><input type="date" id="md"></div><div class="fg"><label>Time</label><input type="time" id="mtime"></div></div><div class="g2"><div class="fg"><label>Duration</label><select id="mdur"><option>30 min</option><option>1 hour</option><option>1.5 hours</option><option>2 hours</option></select></div><div class="fg"><label>Attendees</label><input id="matt" placeholder="Names, comma separated"></div></div><div class="fg"><label>Notes</label><textarea id="mn" placeholder="Meeting notes..."></textarea></div><button class="btn" onclick="addMeeting()">📅 Schedule</button></div><div class="sg"><div class="sb"><div class="v" id="tmeet">0</div><div class="l">Total</div></div><div class="sb"><div class="v" id="umeet">0</div><div class="l">Upcoming</div></div><div class="sb"><div class="v" id="pmeet">0</div><div class="l">Past</div></div></div><div id="mlist"></div>',
'const K="meetings";let meets=JSON.parse(localStorage.getItem(K)||"[]");function save(){localStorage.setItem(K,JSON.stringify(meets))}function addMeeting(){const t=document.getElementById("mt").value.trim();if(!t)return;meets.push({id:Date.now(),title:t,date:document.getElementById("md").value,time:document.getElementById("mtime").value,dur:document.getElementById("mdur").value,att:document.getElementById("matt").value,notes:document.getElementById("mn").value});document.getElementById("mt").value="";document.getElementById("mn").value="";save();render()}function del(id){meets=meets.filter(m=>m.id!==id);save();render()}function render(){meets.sort((a,b)=>new Date(a.date+" "+a.time)-new Date(b.date+" "+b.time));const now=new Date();const list=document.getElementById("mlist");list.innerHTML=meets.map(m=>{const d=new Date(m.date+" "+m.time);const past=d<now;return`<div class="li" style="opacity:${past?.5:1}"><div class="ic">${past?"✅":"📅"}</div><div class="ct"><div class="tt">${m.title}</div><div class="st">${m.date} at ${m.time} • ${m.dur}${m.att?" • "+m.att:""}</div></div><button class="del" onclick="del(${m.id})">✕</button></div>`}).join("")||\'<div class="empty"><span>📅</span>No meetings scheduled</div>\';document.getElementById("tmeet").textContent=meets.length;document.getElementById("umeet").textContent=meets.filter(m=>new Date(m.date+" "+m.time)>=now).length;document.getElementById("pmeet").textContent=meets.filter(m=>new Date(m.date+" "+m.time)<now).length}render()'],

['saas','habit-tracker.html','Habit Tracker','📊','#7c5cff',
'<div class="crd"><div class="flex"><input id="hi" placeholder="Add new habit..." style="margin:0"><button class="btn" onclick="addH()">+ Add</button></div></div><div id="hlist"></div>',
'const K="habits";let habits=JSON.parse(localStorage.getItem(K)||"[]");const today=new Date().toISOString().slice(0,10);function save(){localStorage.setItem(K,JSON.stringify(habits))}function addH(){const n=document.getElementById("hi").value.trim();if(!n)return;habits.push({id:Date.now(),name:n,log:{}});document.getElementById("hi").value="";save();render()}document.getElementById("hi").addEventListener("keydown",e=>{if(e.key==="Enter")addH()});function toggle(id){const h=habits.find(h=>h.id===id);if(h.log[today])delete h.log[today];else h.log[today]=true;save();render()}function del(id){habits=habits.filter(h=>h.id!==id);save();render()}function streak(h){let s=0,d=new Date();for(let i=0;i<365;i++){const k=d.toISOString().slice(0,10);if(h.log[k])s++;else break;d.setDate(d.getDate()-1)}return s}function render(){document.getElementById("hlist").innerHTML=habits.map(h=>{const done=!!h.log[today];const s=streak(h);const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=d.toISOString().slice(0,10);days.push(h.log[k])}return`<div class="crd"><div class="flexb"><div class="flex"><input type="checkbox" ${done?"checked":""} onchange="toggle(${h.id})" style="width:18px;height:18px;accent-color:#7c5cff;margin:0"><span style="font-weight:600;font-size:14px;${done?"text-decoration:line-through;opacity:.5":""}">${h.name}</span></div><div class="flex"><span class="tag">🔥 ${s} day streak</span><button class="del" onclick="del(${h.id})">✕</button></div></div><div style="display:flex;gap:4px;margin-top:10px">${days.map(d=>`<div style="flex:1;height:8px;border-radius:4px;background:${d?"#7c5cff":"rgba(255,255,255,.08)"}"></div>`).join("")}</div></div>`}).join("")||\'<div class="empty"><span>📊</span>No habits yet. Add one above!</div>\'}render()'],

['saas','notes-app.html','Cloud Notes','📝','#7c5cff',
'<div class="flex mb"><input id="ns" placeholder="Search notes..." style="margin:0" oninput="render()"><button class="btn" onclick="addNote()">+ New Note</button></div><div class="g2" id="nlist"></div>',
'const K="notes_data";let notes=JSON.parse(localStorage.getItem(K)||"[]");function save(){localStorage.setItem(K,JSON.stringify(notes))}function addNote(){notes.unshift({id:Date.now(),title:"Untitled Note",body:"",color:"#7c5cff",updated:Date.now()});save();render()}function del(id){notes=notes.filter(n=>n.id!==id);save();render()}function upd(id,field,val){const n=notes.find(n=>n.id===id);n[field]=val;n.updated=Date.now();save()}function render(){const q=document.getElementById("ns").value.toLowerCase();const filtered=notes.filter(n=>n.title.toLowerCase().includes(q)||n.body.toLowerCase().includes(q));document.getElementById("nlist").innerHTML=filtered.map(n=>`<div class="crd" style="border-top:3px solid ${n.color}"><input value="${n.title}" style="font-weight:700;font-size:15px;background:none;border:none;padding:0;margin-bottom:8px" onchange="upd(${n.id},\'title\',this.value)"><textarea style="min-height:60px" onchange="upd(${n.id},\'body\',this.value)">${n.body}</textarea><div class="flexb mt"><span style="font-size:10px;color:#555">${new Date(n.updated).toLocaleString()}</span><button class="del" onclick="del(${n.id})">🗑️</button></div></div>`).join("")||\'<div class="empty" style="grid-column:1/-1"><span>📝</span>No notes yet</div>\'}render()'],

['saas','bookmark-manager.html','Bookmark Manager','🔖','#7c5cff',
'<div class="crd"><div class="g2"><input id="bn" placeholder="Bookmark name"><input id="bu" placeholder="https://..."></div><div class="g2"><select id="bc"><option>General</option><option>Dev</option><option>Design</option><option>News</option><option>Learning</option></select><button class="btn" onclick="addBm()">+ Save</button></div></div><div class="tabs" id="btabs"></div><div id="blist"></div>',
'const K="bookmarks";let bms=JSON.parse(localStorage.getItem(K)||"[]");let bfilter="All";function save(){localStorage.setItem(K,JSON.stringify(bms))}function addBm(){const n=document.getElementById("bn").value.trim(),u=document.getElementById("bu").value.trim();if(!n||!u)return;bms.push({id:Date.now(),name:n,url:u,cat:document.getElementById("bc").value});document.getElementById("bn").value="";document.getElementById("bu").value="";save();render()}function del(id){bms=bms.filter(b=>b.id!==id);save();render()}function setF(f,btn){bfilter=f;document.querySelectorAll(".tab").forEach(t=>t.classList.remove("on"));btn.classList.add("on");render()}function render(){const cats=["All",...new Set(bms.map(b=>b.cat))];document.getElementById("btabs").innerHTML=cats.map(c=>`<button class="tab ${c===bfilter?"on":""}" onclick="setF(\'${c}\',this)">${c}</button>`).join("");const filtered=bfilter==="All"?bms:bms.filter(b=>b.cat===bfilter);document.getElementById("blist").innerHTML=filtered.map(b=>`<div class="li"><div class="ic">🔗</div><div class="ct"><div class="tt">${b.name}</div><div class="st">${b.url}</div></div><span class="tag">${b.cat}</span><a href="${b.url}" target="_blank" style="color:#7c5cff;text-decoration:none;font-size:12px">Open ↗</a><button class="del" onclick="del(${b.id})">✕</button></div>`).join("")||\'<div class="empty"><span>🔖</span>No bookmarks saved</div>\'}render()'],
];

// Write each app
apps.forEach(([folder, file, title, icon, accent, body, script]) => {
  const dir = path.join(base, folder);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, file), tmpl(title, icon, accent, body, script), 'utf8');
});

console.log(`Generated ${apps.length} functional apps`);
